---
title: "Data"
output: html_document
---

## Download
<iframe height="1000px" width=1000px frameBorder="0" src="https://ahyounglim.shinyapps.io/OpenDengue/"> </iframe>


### Download global data

Please visit our [git repository](https://github.com/OpenDengue/master-repo/tree/d94409df15c35787108f21738dcf6d87bf7f4d61/data/releases/V1) to download OpenDengue global national, highest temporal and highest spatial data. 


### Suggested citation

"The OpenDengue database, Version 1.1, 2023, https://opendengue.org/, Accesssed [today's date]"
<br>
<br>

## Data definitions
The OpenDengue dataset contains reported total case counts with each row corresponds to a unique location and time. 

Where reported, we include dengue cases at all levels of severity (dengue, dengue with/without warning signs, severe dengue, dengue haemorhaggic fever, dengue shock syndrome, dengue deaths) and methods of confirmation (suspected, probable, clinically confirmed, laboratory confirmed) in the variable `dengue_total`. The specific case definition used for a particular data point  will depend on the original data source. The data source can be identified by looking up the record `sourceID` in the `metadata.xlsx` file which can be found in the [OpenDengue Github repo](https://github.com/OpenDengue/master-repo). This will include a URL reference to the original public data source. Future versions of the OpenDengue data set will dissaggregate data by severity and method of confirmation where reported.

<br>
Location is encoded by text name at national (`adm_0_name`) and sub-national (`adm_1_name` and `adm_2_name`) level. Records are matched to Global Administrative Unit Layers (GAUL, see [UN FAO website](https://data.apps.fao.org/catalog/dataset/gaul-codes)) codes (`FAO_GAUL_code`, Admin0-2) and [Natural Earth](https://www.naturalearthdata.com) shapefiles (downloadable via the `rnaturalearth` [R package](https://github.com/ropensci/rnaturalearth)) using [ISO alpha-3](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) (admin0) and [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) (admin1) standards.

<br>
Time periods are recorded using a start date (`calendar_start_date`) and end date (`calendar_end_date`) with the format `YYYY-mm-dd`.

## Limitations
* Dengue surveillance, reporting and accessibility of data varies between countries, sources and, sometimes, over time which can make comparisons invalid. Please check the consistency  of original sources if making comparisons.
* In all countries reported cases are likely to only be a small subset of total dengue infections due to many asymptomatic and sub-clinical infections.


```{r echo=FALSE}
require(dplyr);require(metathis)

meta() %>%
  meta_description(
    "The OpenDengue project aims to build and maintain a database of dengue case counts for every dengue-affected country worldwide since 1990. We collate data from a range of publicly available sources including ministry of health websites, peer-reviewed publications and other disease databases."
  ) %>% 
  
  meta_social(
    title = "OpenDengue: Data",
    url = "opendengue.org",
    image = "https://raw.githubusercontent.com/OpenDengue/master-repo/main/docs/logo/thumbnail.png",
    twitter_card_type = "summary_large_image",
    twitter_creator = "@OliverBrady1",
    image_alt = "OpenDengue Logo",
    og_type = "website"

  )
```
